package es.ulpgc;

public enum AminoAcid {
    PHENYLALANINE, LEUCINE, ISOLEUCINE, METHIONINE, VALINE, SERINE, PROLINE, THREONINE, ALANINE, TYROSINE, HISTIDINE,
    GLUTAMINE, ASPARAGINE, LYSINE, ASPARTIC_ACID, GLUTAMIC_ACID, CYSTEINE, TRYPTOPHAN, ARGININE, GLYCINE
}
